import { useEffect, useRef, useState } from "react";
import { ChevronDown, ChevronUp, Eye, EyeOff, ImageUp, LogOut, PackagePlus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import "./Admin.css";
import "./AdminCards.css";

const textFields = [
  ["brand.primary", "اسم العلامة — السطر الأول"], ["brand.secondary", "اسم العلامة — السطر الثاني"], ["nav.menu", "رابط المنيو في أعلى الموقع"], ["nav.delivery", "رابط التوصيل في أعلى الموقع"], ["nav.reviews", "رابط آراء العملاء في أعلى الموقع"], ["nav.contact", "رابط التواصل في أعلى الموقع"], ["nav.order", "زر اطلب الآن في الأعلى"], ["mobile.order", "زر الطلب في قائمة الجوال"],
  ["home.eyebrow", "النص الصغير أعلى العنوان"], ["home.title.primary", "العنوان الرئيسي"], ["home.title.accent", "تكملة العنوان"], ["home.description", "وصف البداية"], ["home.note", "ملاحظة بجانب زر الطلب"], ["home.sticker", "نص بطاقة اختيار اليوم"], ["home.sideNote", "النص العمودي بجانب الصورة"], ["home.heroAlt", "وصف الصورة الرئيسية"],
  ["order.cta", "زر الطلب في البداية"], ["order.typeNormal", "اسم النوع الأول"], ["order.typeSpicy", "اسم النوع الثاني"], ["order.sectionLabel", "اسم قسم المنيو"], ["order.title", "عنوان قسم المنيو"], ["order.accent", "تكملة عنوان المنيو"], ["order.description", "شرح طريقة المنيو"], ["order.typeLead", "النص الصغير فوق اختيار النوع"], ["order.typeTitle", "عنوان اختيار النوع"], ["order.itemsLead", "النص الصغير فوق الأصناف"], ["order.itemsTitle", "عنوان قائمة الأصناف"], ["order.selectedType", "وصف النوع المختار"], ["order.typeNote", "ملاحظة تبديل النوع"], ["order.summaryTitle", "عنوان ملخص الطلب"], ["order.emptyCart", "رسالة السلة الفارغة"], ["order.totalLabel", "عنوان الإجمالي"], ["order.submit", "زر إرسال الطلب"], ["order.note", "ملاحظة أسفل ملخص الطلب"], ["order.messageIntro", "افتتاحية رسالة واتساب"], ["order.customerNameLabel", "حقل الاسم في رسالة واتساب"], ["order.locationLabel", "حقل اللوكيشن في رسالة واتساب"], ["order.buildingLabel", "حقل رقم العمارة في رسالة واتساب"], ["order.floorLabel", "حقل الدور في رسالة واتساب"], ["order.apartmentLabel", "حقل الشقة في رسالة واتساب"], ["order.confirmationNotice", "تنبيه تأكيد الطلب في رسالة واتساب"],
  ["delivery.label", "عنوان قسم التوصيل"], ["delivery.title", "العنوان الرئيسي للتوصيل"], ["delivery.accent", "تكملة عنوان التوصيل"], ["delivery.areas", "مناطق التوصيل"], ["delivery.points", "نقاط التوصيل المتاحة"], ["delivery.pickup", "نقطة الاستلام"], ["delivery.prepTime", "نص الحجز والتجهيز"], ["delivery.eta", "وقت التوصيل"], ["delivery.cta", "زر الطلب في التوصيل"], ["payment.methods", "طرق الدفع"],
  ["reviews.label", "عنوان قسم آراء العملاء"], ["reviews.title", "العنوان الرئيسي للآراء"], ["reviews.accent", "تكملة عنوان الآراء"], ["reviews.empty", "رسالة عدم وجود آراء"], ["reviews.read", "نص فتح صورة الرأي"],
  ["contact.label", "عنوان قسم التواصل"], ["contact.title", "العنوان الرئيسي للتواصل"], ["contact.accent", "تكملة عنوان التواصل"], ["contact.instagramLabel", "اسم Instagram الظاهر"], ["contact.instagramHandle", "معرّف Instagram الظاهر"], ["contact.tiktokLabel", "اسم TikTok الظاهر"], ["contact.tiktokHint", "وصف زر TikTok"], ["contact.whatsappLabel", "عنوان زر واتساب"], ["contact.whatsappHint", "نص زر واتساب"], ["footer.description", "وصف التذييل"], ["footer.order", "زر واتساب الطلبات في التذييل"],
] as const;
const defaultTextValues: Record<string, string> = {
  "brand.primary": "ورق العنب", "brand.secondary": "اللذيذ", "nav.menu": "المنيو", "nav.delivery": "التوصيل", "nav.reviews": "آراء العملاء", "nav.contact": "تواصل", "nav.order": "اطلب الآن", "mobile.order": "إرسال طلب عبر واتساب",
  "home.eyebrow": "ورق عنب منزلي في القاهرة", "home.title.primary": "لفّة متظبطة.", "home.title.accent": "قعدة مبسوطة.", "home.description": "اختار نوع ورق العنب، ثم زِد العدد جنب كل صنف.", "home.note": "طازج عند الطلب", "home.sticker": "اختيار اليوم", "home.sideNote": "من جدة إلى القاهرة — صُنع بكل حب وأعلى جودة", "home.heroAlt": "صينية ورق عنب محضرة طازجة بالليمون",
  "order.cta": "اطلب من المنيو", "order.typeNormal": "عادي", "order.typeSpicy": "حار", "order.sectionLabel": "المنيو", "order.title": "اطلبها", "order.accent": "بسهولة.", "order.description": "اختر النوع أولًا، ثم أضف الصنف والعدد. يمكنك تبديل النوع وإضافة الصنف نفسه مجددًا.", "order.typeLead": "أولًا", "order.typeTitle": "حدد النوع الذي ستضيفه الآن", "order.itemsLead": "أضف بالعدد الذي تريده", "order.itemsTitle": "كل الأصناف في منيو واحد", "order.selectedType": "النوع المضاف الآن", "order.typeNote": "بدّل بين عادي وحار ثم أضف الصنف نفسه مرة أخرى إن رغبت.", "order.summaryTitle": "ملخص طلبك", "order.emptyCart": "اختر النوع ثم زِد العدد بجانب الصنف المطلوب.", "order.totalLabel": "الإجمالي النهائي", "order.submit": "إرسال الطلب", "order.note": "سيظهر النوع والكميات في رسالة واتساب.", "order.messageIntro": "أهلًا، أريد طلب من ورق العنب اللذيذ:", "order.customerNameLabel": "الاسم", "order.locationLabel": "اللوكيشن (رابط Google Maps أو مشاركة الموقع)", "order.buildingLabel": "رقم العمارة", "order.floorLabel": "الدور", "order.apartmentLabel": "الشقة", "order.confirmationNotice": "لتأكيد الطلب لازم المعلومات كاملة.",
  "delivery.label": "التوصيل", "delivery.title": "من مطبخنا", "delivery.accent": "لبيتك.", "delivery.areas": "توصيل لجميع أنحاء القاهرة", "delivery.points": "نقاط التوصيل المتاحة: فيصل وأكتوبر", "delivery.pickup": "استلام من الثلاثيني — فيصل", "delivery.prepTime": "يفضل الحجز قبل يوم حتى الساعة 12، أو حسب الكمية المتوفرة", "delivery.eta": "وقت التوصيل يختلف حسب المنطقة", "delivery.cta": "اطلب الآن", "payment.methods": "الدفع: كاش، فودافون كاش، أو إنستاباي",
  "reviews.label": "آراء العملاء", "reviews.title": "تجارب", "reviews.accent": "من عملائنا.", "reviews.empty": "ستظهر هنا صور آراء العملاء التي تضيفها من لوحة المالك.", "reviews.read": "اضغط للقراءة",
  "contact.label": "تواصل", "contact.title": "تابعنا وخليك", "contact.accent": "قريب من الجديد.", "contact.instagramLabel": "Instagram", "contact.instagramHandle": "@delicious_grape_leaves94", "contact.tiktokLabel": "TikTok", "contact.tiktokHint": "@delicious_grape_leaves", "contact.whatsappLabel": "WhatsApp", "contact.whatsappHint": "للاستفسارات والتواصل مباشرة", "footer.description": "من مطبخنا لبيتك في القاهرة.", "footer.order": "واتساب الطلبات",
};
const imageSlots = [["hero-main", "الصورة الرئيسية"], ["hero-side", "الصورة الجانبية"], ["packaging", "صورة التغليف"]] as const;
const contactFields = [["contact.whatsapp", "واتساب الطلبات"], ["contact.instagram", "رابط Instagram"], ["contact.tiktok", "رابط TikTok"], ["delivery.areas", "مناطق التوصيل"], ["delivery.pickup", "نقطة الاستلام"], ["delivery.prepTime", "وقت الحجز والتجهيز"], ["delivery.eta", "وقت التوصيل"], ["payment.methods", "طرق الدفع"]] as const;

export default function Admin() {
  const { data: user, isLoading } = trpc.auth.me.useQuery();
  const dashboard = trpc.admin.dashboard.useQuery(undefined, { enabled: Boolean(user) });
  const utils = trpc.useUtils();
  const [isAddingProduct, setIsAddingProduct] = useState(false);
  const [newProduct, setNewProduct] = useState({ slug: "", nameAr: "", nameEn: null, descriptionAr: "", descriptionEn: null, category: "ورق عنب", price: 0, currency: "EGP", sortOrder: 99, isVisible: true, isArchived: false });
  const saveSetting = trpc.admin.settings.save.useMutation({ onSuccess: () => { toast.success("تم الحفظ."); utils.admin.dashboard.invalidate(); } });
  const resetSetting = trpc.admin.settings.reset.useMutation({ onSuccess: () => { toast.success("تمت إعادة النص إلى قيمته الافتراضية."); utils.admin.dashboard.invalidate(); } });
  const updateProduct = trpc.admin.products.update.useMutation({ onSuccess: () => { toast.success("تم حفظ الصنف."); utils.admin.dashboard.invalidate(); } });
  const createProduct = trpc.admin.products.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة الصنف."); setIsAddingProduct(false); setNewProduct({ slug: "", nameAr: "", nameEn: null, descriptionAr: "", descriptionEn: null, category: "ورق عنب", price: 0, currency: "EGP", sortOrder: 99, isVisible: true, isArchived: false }); utils.admin.dashboard.invalidate(); } });
  const archiveProduct = trpc.admin.products.archive.useMutation({ onSuccess: () => { toast.success("تمت إزالة الصنف من المنيو."); utils.admin.dashboard.invalidate(); } });
  const removeImage = trpc.admin.images.remove.useMutation({ onSuccess: () => { toast.success("تمت إزالة الصورة من الموقع."); utils.admin.dashboard.invalidate(); } });
  const updateReview = trpc.admin.reviews.update.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة صورة الرأي."); utils.admin.dashboard.invalidate(); } });
  const reorderReviews = trpc.admin.reviews.reorder.useMutation({ onSuccess: () => { toast.success("تم حفظ ترتيب صور الآراء."); utils.admin.dashboard.invalidate(); } });
  const removeReview = trpc.admin.reviews.remove.useMutation({ onSuccess: () => { toast.success("تم حذف صورة الرأي."); utils.admin.dashboard.invalidate(); } });
  const [tab, setTab] = useState<"menu"|"texts"|"images"|"reviews"|"contact">("menu");
  const fileInputs = useRef<Record<string, HTMLInputElement | null>>({});
  useEffect(() => { if (!isLoading && !user) window.location.assign("/api/admin/google/login"); }, [isLoading, user]);
  if (isLoading || !user) return <main className="admin-loading">جارٍ التحقق من صلاحية الدخول…</main>;
  const settings = Object.fromEntries((dashboard.data?.settings ?? []).map(item => [item.key, item.value]));
  const images = Object.fromEntries((dashboard.data?.images ?? []).map(item => [item.slot, item]));
  const upload = async (slot: string, labelAr: string, file?: File) => {
    if (!file) return toast.error("اختر صورة من الكمبيوتر أولًا.");
    const dataBase64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
    const response = await fetch("/api/admin/images/upload", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slot, labelAr, altAr: labelAr, mimeType: file.type, dataBase64 }) });
    if (!response.ok) return toast.error("تعذر رفع الصورة.");
    toast.success("تم استبدال الصورة."); utils.admin.dashboard.invalidate();
  };
  const uploadReview = async (file?: File) => {
    if (!file) return toast.error("اختر صورة رأي من الكمبيوتر أولًا.");
    const dataBase64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
    const response = await fetch("/api/admin/reviews/upload", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slot: `review-${Date.now()}`, labelAr: "رأي عميل", altAr: "صورة رأي عميل", mimeType: file.type, dataBase64 }) });
    if (!response.ok) return toast.error("تعذر رفع صورة الرأي.");
    toast.success("تمت إضافة صورة الرأي."); utils.admin.dashboard.invalidate();
  };
  const saveText = (key: string, label: string, value: string) => saveSetting.mutate({ key, group: "محتوى الموقع", value });
  const confirmAction = (message: string, action: () => void) => { if (window.confirm(message)) action(); };
  return <main className="admin-shell" dir="rtl"><aside className="admin-side"><div><p>لوحة المالك</p><h1>ورق العنب<br/>اللذيذ</h1></div><nav>{[["menu","المنيو والأسعار"],["texts","نصوص الموقع"],["images","صور الموقع"],["reviews","آراء العملاء"],["contact","التواصل والتوصيل"]].map(([id,label]) => <button key={id} onClick={() => { setTab(id as typeof tab); document.getElementById(`admin-${id}`)?.scrollIntoView({ behavior: "smooth", block: "start" }); }}>{label}</button>)}</nav><div className="admin-account"><strong>{user.name || "المالك"}</strong><small>{user.email}</small><button onClick={async () => { await fetch("/api/admin/logout", { method: "POST", credentials: "include" }); window.location.assign("/"); }}><LogOut size={15}/> خروج</button></div></aside><section className="admin-content"><header><div><p>إدارة الموقع</p><h2>{tab === "menu" ? "المنيو والأسعار" : tab === "texts" ? "نصوص الموقع" : tab === "images" ? "صور الموقع" : tab === "reviews" ? "آراء العملاء" : "التواصل والتوصيل"}</h2></div><a href="/" target="_blank">عرض الموقع</a></header>
  <section id="admin-menu" className="admin-panel"><div className="panel-heading"><div><span>01</span><div><p>المنيو</p><h3>كل صنف في بطاقة خاصة</h3></div></div><button onClick={() => setIsAddingProduct(true)}><PackagePlus size={16}/> إضافة صنف</button></div><div className="edit-card-grid">{isAddingProduct && <ProductCard product={newProduct} heading="صنف جديد غير محفوظ" onSave={(data) => { if (!data.nameAr.trim()) return toast.error("اكتب اسم الصنف قبل الحفظ."); createProduct.mutate({ ...newProduct, ...data, slug: newProduct.slug || `menu-${Date.now()}` }); }} onCancel={() => setIsAddingProduct(false)}/>} {dashboard.data?.products.map(product => <ProductCard key={product.id} product={product} onSave={(data) => updateProduct.mutate({ id: product.id, data })} onArchive={() => confirmAction(`هل تريد إزالة «${product.nameAr}» من المنيو؟ يمكن استعادته من قاعدة البيانات لاحقًا.`, () => archiveProduct.mutate({ id: product.id }))}/>) || <p className="empty-admin">أضف أول صنف ليظهر هنا.</p>}</div></section>
  <section className="admin-panel"><div className="panel-heading"><div><span>02</span><div><p>نصوص الموقع</p><h3>كل نص بعنوان واضح</h3></div></div><small>غيّر النص ثم احفظه من بطاقته.</small></div><div className="edit-card-grid">{textFields.map(([key,label]) => <TextCard key={key} label={label} value={settings[key] ?? defaultTextValues[key] ?? ""} onSave={(value) => saveText(key,label,value)} onReset={() => confirmAction(`هل تريد حذف التعديل على «${label}» وإرجاع النص الافتراضي؟`, () => resetSetting.mutate({ key }))}/>)}</div></section>
  <section className="admin-panel"><div className="panel-heading"><div><span>03</span><div><p>صور الموقع</p><h3>استبدل كل صورة من الكمبيوتر</h3></div></div><small>JPEG أو PNG أو WebP حتى 5 م.ب.</small></div><div className="edit-card-grid">{imageSlots.map(([slot,label]) => <article className="edit-card" key={slot}><h4>{label}</h4>{images[slot]?.url ? <img src={images[slot].url} alt={label}/> : <div className="empty-admin">لا توجد صورة مرفوعة بعد.</div>}<input ref={node => { fileInputs.current[slot] = node; }} type="file" accept="image/jpeg,image/png,image/webp"/><button onClick={() => upload(slot,label,fileInputs.current[slot]?.files?.[0])}><ImageUp size={16}/> رفع من الكمبيوتر</button>{images[slot]?.url && <button className="danger-button" onClick={() => confirmAction(`هل تريد إزالة «${label}»؟ سيعود الموقع إلى الصورة الافتراضية عند توفرها.`, () => removeImage.mutate({ slot }))}><Trash2 size={16}/> حذف الصورة</button>}</article>)}</div></section>
  <section id="admin-reviews" className="admin-panel"><div className="panel-heading"><div><span>04</span><div><p>آراء العملاء</p><h3>أضف صور الآراء الحقيقية</h3></div></div><small>لن يظهر في الموقع إلا ما ترفعه أنت.</small></div><div className="image-upload"><input ref={node => { fileInputs.current["review-new"] = node; }} type="file" accept="image/jpeg,image/png,image/webp"/><button onClick={() => uploadReview(fileInputs.current["review-new"]?.files?.[0])}><ImageUp size={16}/> رفع صورة رأي من الكمبيوتر</button></div><div className="image-grid">{dashboard.data?.reviewImages.map((review, index, allReviews) => <figure key={review.id}><img src={review.url} alt={review.altAr || review.labelAr}/><figcaption><strong>{review.labelAr}</strong><div className="review-card-actions"><button disabled={index === 0} onClick={() => { const ids = allReviews.map(item => item.id); [ids[index - 1], ids[index]] = [ids[index], ids[index - 1]]; reorderReviews.mutate({ ids }); }}><ChevronUp size={15}/> لأعلى</button><button disabled={index === allReviews.length - 1} onClick={() => { const ids = allReviews.map(item => item.id); [ids[index], ids[index + 1]] = [ids[index + 1], ids[index]]; reorderReviews.mutate({ ids }); }}><ChevronDown size={15}/> لأسفل</button><button onClick={() => updateReview.mutate({ id: review.id, isVisible: !review.isVisible })}>{review.isVisible ? <><EyeOff size={15}/> إخفاء</> : <><Eye size={15}/> إظهار</>}</button><button className="danger-button" onClick={() => confirmAction("هل تريد حذف صورة الرأي نهائيًا من الموقع؟", () => removeReview.mutate({ id: review.id }))}><Trash2 size={15}/> حذف</button></div></figcaption></figure>) || <p className="empty-admin">لا توجد آراء مرفوعة بعد.</p>}</div></section>
  <section className="admin-panel"><div className="panel-heading"><div><span>05</span><div><p>التواصل</p><h3>الحسابات والتوصيل</h3></div></div><small>كل قيمة في بطاقة مستقلة.</small></div><div className="edit-card-grid">{contactFields.map(([key,label]) => <TextCard key={key} label={label} value={settings[key] ?? defaultTextValues[key] ?? ""} onSave={(value) => saveSetting.mutate({ key, group: "تواصل وتوصيل", value })} onReset={() => confirmAction(`هل تريد حذف التعديل على «${label}» وإرجاع القيمة الافتراضية؟`, () => resetSetting.mutate({ key }))}/>)}</div></section>
  </section></main>;
}

function TextCard({ label, value, onSave, onReset }: { label: string; value: string; onSave: (value: string) => void; onReset: () => void }) { const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]); return <article className="edit-card"><h4>{label}</h4><label><textarea value={draft} onChange={event => setDraft(event.target.value)}/></label><button onClick={() => onSave(draft)}><Save size={16}/> حفظ {label}</button><button className="danger-button" onClick={onReset}><Trash2 size={16}/> حذف التعديل</button></article>; }
function ProductCard({ product, onSave, onArchive, onCancel, heading }: { product: any; onSave: (data: any) => void; onArchive?: () => void; onCancel?: () => void; heading?: string }) { const [draft, setDraft] = useState(product); useEffect(() => setDraft(product), [product]); return <article className="edit-card"><h4>{heading || draft.nameAr}</h4><label>اسم الصنف<input value={draft.nameAr} onChange={event => setDraft({ ...draft, nameAr: event.target.value })}/></label><label>الوصف<textarea value={draft.descriptionAr || ""} onChange={event => setDraft({ ...draft, descriptionAr: event.target.value })}/></label><label>السعر بالجنيه<input type="number" value={draft.price} onChange={event => setDraft({ ...draft, price: Number(event.target.value) })}/></label><label>القسم<input value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value })}/></label><button onClick={() => onSave({ nameAr: draft.nameAr, descriptionAr: draft.descriptionAr, price: draft.price, category: draft.category })}><Save size={16}/> حفظ هذا الصنف</button>{onArchive && <button className="danger-button" onClick={onArchive}><Trash2 size={16}/> إزالة من المنيو</button>}{onCancel && <button className="danger-button" onClick={onCancel}>إلغاء الإضافة</button>}</article>; }
