/** Google-owner administration page: public navigation never links to this route. */
import { useEffect, useRef, useState } from "react";
import { Eye, EyeOff, ImageUp, LogOut, PackagePlus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import "./Admin.css";
import "./AdminCards.css";

const blankProduct = { slug: "", nameAr: "", nameEn: "", descriptionAr: "", descriptionEn: "", category: "ورق عنب", price: 0, currency: "EGP", sortOrder: 0, isVisible: true, isArchived: false };

export default function Admin() {
  const { data: user, isLoading } = trpc.auth.me.useQuery();
  const dashboard = trpc.admin.dashboard.useQuery(undefined, { enabled: Boolean(user) });
  const utils = trpc.useUtils();
  const createProduct = trpc.admin.products.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة الصنف."); utils.admin.dashboard.invalidate(); setForm(blankProduct); } });
  const updateProduct = trpc.admin.products.update.useMutation({ onSuccess: () => { toast.success("تم الحفظ."); utils.admin.dashboard.invalidate(); } });
  const archiveProduct = trpc.admin.products.archive.useMutation({ onSuccess: () => { toast.success("تم تعطيل الصنف."); utils.admin.dashboard.invalidate(); } });
  const saveSetting = trpc.admin.settings.save.useMutation({ onSuccess: () => { toast.success("تم حفظ النص أو الإعداد."); utils.admin.dashboard.invalidate(); } });
  const [form, setForm] = useState(blankProduct);
  const [editingProductId, setEditingProductId] = useState<number | null>(null);
  const [setting, setSetting] = useState({ key: "", group: "عام", value: "" });
  const [upload, setUpload] = useState({ slot: "", labelAr: "", altAr: "" });
  const fileInput = useRef<HTMLInputElement>(null);

  useEffect(() => { if (!isLoading && !user) window.location.assign("/api/admin/google/login"); }, [isLoading, user]);
  if (isLoading || !user) return <main className="admin-loading">جارٍ التحقق من صلاحية الدخول…</main>;

  const submitProduct = (event: React.FormEvent) => {
    event.preventDefault();
    const data = { ...form, nameEn: form.nameEn || null, descriptionAr: form.descriptionAr || null, descriptionEn: form.descriptionEn || null };
    if (editingProductId) updateProduct.mutate({ id: editingProductId, data }, { onSuccess: () => { setEditingProductId(null); setForm(blankProduct); } });
    else createProduct.mutate(data);
  };
  const handleUpload = async (file?: File, asReview = false) => {
    if (!file || !upload.slot || !upload.labelAr) return toast.error("أدخل موضع الصورة واسمها ثم اختر ملفًا.");
    if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024) return toast.error("اختر JPEG أو PNG أو WebP بحجم لا يتجاوز 5 م.ب.");
    const dataBase64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
    const response = await fetch(asReview ? "/api/admin/reviews/upload" : "/api/admin/images/upload", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...upload, mimeType: file.type, dataBase64 }) });
    if (!response.ok) return toast.error("تعذر رفع الصورة.");
    toast.success(asReview ? "تم حفظ صورة الرأي." : "تم حفظ الصورة."); setUpload({ slot: "", labelAr: "", altAr: "" }); if (fileInput.current) fileInput.current.value = ""; utils.admin.dashboard.invalidate();
  };

  return <main className="admin-shell" dir="rtl"><aside className="admin-side"><div><p>لوحة المالك</p><h1>ورق العنب<br />اللذيذ</h1></div><nav><a href="#products">المنيو والأسعار</a><a href="#copy">نصوص الموقع</a><a href="#images">صور الموقع</a><a href="#reviews">آراء العملاء</a><a href="#accounts">الحسابات وواتساب</a></nav><div className="admin-account"><strong>{user.name || "المالك"}</strong><small>{user.email}</small><button onClick={async () => { await fetch("/api/admin/logout", { method: "POST", credentials: "include" }); window.location.assign("/"); }}><LogOut size={15} /> خروج</button></div></aside><section className="admin-content"><header><div><p>إدارة الموقع</p><h2>كل تعديل هنا يظهر في موقع القاهرة بعد الحفظ.</h2></div><a href="/" target="_blank">عرض الموقع</a></header>
    <section id="products" className="admin-panel"><div className="panel-heading"><div><span>01</span><div><p>المنيو</p><h3>إدارة المنتجات</h3></div></div><small>أضف أو عدّل أو أخفِ أو عطّل الأصناف.</small></div><form className="product-form" onSubmit={submitProduct}><input required placeholder="معرّف مختصر مثل grape-20" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /><input required placeholder="اسم الصنف بالعربية" value={form.nameAr} onChange={e => setForm({ ...form, nameAr: e.target.value })} /><input placeholder="الاسم بالإنجليزية (اختياري)" value={form.nameEn} onChange={e => setForm({ ...form, nameEn: e.target.value })} /><input required type="number" min="0" placeholder="السعر بالجنيه" value={form.price || ""} onChange={e => setForm({ ...form, price: Number(e.target.value) })} /><input placeholder="القسم: ورق عنب، فتة…" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} /><input type="number" placeholder="ترتيب العرض" value={form.sortOrder} onChange={e => setForm({ ...form, sortOrder: Number(e.target.value) })} /><textarea placeholder="وصف عربي مختصر" value={form.descriptionAr} onChange={e => setForm({ ...form, descriptionAr: e.target.value })} /><button disabled={createProduct.isPending || updateProduct.isPending}>{editingProductId ? <><Save size={16} /> حفظ التعديل</> : <><PackagePlus size={16} /> إضافة الصنف</>}</button>{editingProductId && <button type="button" className="secondary-form" onClick={() => { setEditingProductId(null); setForm(blankProduct); }}>إلغاء</button>}</form><div className="admin-products">{dashboard.data?.products.map(product => <article key={product.id}><div><strong>{product.nameAr}</strong><span>{product.category} · {product.price} ج.م</span></div><div><button onClick={() => { setEditingProductId(product.id); setForm({ slug: product.slug, nameAr: product.nameAr, nameEn: product.nameEn || "", descriptionAr: product.descriptionAr || "", descriptionEn: product.descriptionEn || "", category: product.category, price: product.price, currency: product.currency, sortOrder: product.sortOrder, isVisible: product.isVisible, isArchived: product.isArchived }); window.scrollTo({ top: 0, behavior: "smooth" }); }}><Save size={15} /> تعديل</button><button onClick={() => updateProduct.mutate({ id: product.id, data: { isVisible: !product.isVisible } })}>{product.isVisible ? <><EyeOff size={15} /> إخفاء</> : <><Eye size={15} /> إظهار</>}</button><button className="danger" onClick={() => { if (confirm(`تعطيل ${product.nameAr}؟`)) archiveProduct.mutate({ id: product.id }); }}><Trash2 size={15} /> تعطيل</button></div></article>) || <p className="empty-admin">لم تضف أي منتجات بعد. المنتجات الافتراضية في الموقع ستبقى ظاهرة إلى أن تربطها بالبيانات.</p>}</div></section>
    <section id="copy" className="admin-panel"><div className="panel-heading"><div><span>02</span><div><p>المحتوى</p><h3>نصوص وإعدادات الموقع</h3></div></div><small>مثال: العنوان الرئيسي، واتساب، TikTok، مناطق التوصيل.</small></div><form className="setting-form" onSubmit={e => { e.preventDefault(); saveSetting.mutate(setting); }}><input required placeholder="مفتاح مثل contact.whatsapp" value={setting.key} onChange={e => setSetting({ ...setting, key: e.target.value })} /><input required placeholder="المجموعة: تواصل / رئيسية / توصيل" value={setting.group} onChange={e => setSetting({ ...setting, group: e.target.value })} /><textarea required placeholder="النص أو الرابط أو القيمة" value={setting.value} onChange={e => setSetting({ ...setting, value: e.target.value })} /><button disabled={saveSetting.isPending}><Save size={16} /> حفظ</button></form><div className="settings-list">{dashboard.data?.settings.map(item => <button type="button" key={item.key} onClick={() => setSetting({ key: item.key, group: item.group, value: item.value })}><strong>{item.key}</strong><span>{item.group}</span><p>{item.value}</p></button>) || <p className="empty-admin">لا توجد نصوص محفوظة بعد.</p>}</div></section>
    <section id="images" className="admin-panel"><div className="panel-heading"><div><span>03</span><div><p>الصور</p><h3>صور الموقع وآراء العملاء</h3></div></div><small>JPEG وPNG وWebP حتى 5 م.ب.</small></div><div className="image-upload"><input placeholder="موضع الصورة مثل hero-main" value={upload.slot} onChange={e => setUpload({ ...upload, slot: e.target.value })} /><input placeholder="اسمها في الإدارة أو عنوان الرأي" value={upload.labelAr} onChange={e => setUpload({ ...upload, labelAr: e.target.value })} /><input placeholder="وصف بديل للصورة (اختياري)" value={upload.altAr} onChange={e => setUpload({ ...upload, altAr: e.target.value })} /><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" /><button onClick={() => handleUpload(fileInput.current?.files?.[0])}><ImageUp size={16} /> رفع كصورة موقع</button><button onClick={() => handleUpload(fileInput.current?.files?.[0], true)}><ImageUp size={16} /> رفع كرأي عميل</button></div><div className="image-grid">{dashboard.data?.images.map(image => <figure key={image.slot}><img src={image.url} alt={image.altAr || image.labelAr} /><figcaption><strong>{image.labelAr}</strong><span>{image.slot}</span></figcaption></figure>) || <p className="empty-admin">لا توجد صور موقع مرفوعة بعد.</p>}</div></section><section id="accounts" className="admin-panel"><div className="panel-heading"><div><span>04</span><div><p>التواصل</p><h3>الحسابات وواتساب</h3></div></div><small>اختر الحقل المطلوب ثم اكتب قيمته واحفظها.</small></div><div className="admin-products">{[["واتساب الطلبات","contact.whatsapp","تواصل"],["رابط TikTok","contact.tiktok","تواصل"],["مناطق التوصيل","delivery.areas","توصيل"],["نقطة الاستلام","delivery.pickup","توصيل"],["طرق الدفع","payment.methods","دفع"]].map(([label,key,group]) => <article key={key}><strong>{label}</strong><button onClick={() => { setSetting({ key, group, value: dashboard.data?.settings.find(item => item.key === key)?.value || "" }); document.getElementById("copy")?.scrollIntoView({ behavior: "smooth" }); }}>تعديل</button></article>)}</div></section>
  </section></main>;
}
